@BASE_URL = http://localhost:8000/api/v1

POST {{BASE_URL}}/register/
Content-Type: application/json

{
  "username": "user1",
  "first_name": "Иван",
  "last_name": "Иванов",
  "email": "sdmarch213@gmail.com",
  "password": "password123"
}

###

POST {{BASE_URL}}/register/
Content-Type: application/json

{
  "username": "user2",
  "first_name": "Иван1",
  "last_name": "Иванов1",
  "email": "doshamine@gmail.com",
  "password": "password123"
}

###

POST {{BASE_URL}}/login/
Content-Type: application/json

{
  "username": "user2",
  "password": "password123"
}

###

GET {{BASE_URL}}/products/
Content-Type: application/json
Authorization: Token 3a332e5268ed86c06ff5e1c9ec8a7f4320aa5ac0

###

POST {{BASE_URL}}/orders/
Content-Type: application/json
Authorization: Token 159a35622c240a0052b168c692ab918be83a6f9c

{
  "order_items": [
    {
      "product": 1235464569,
      "shop": 1,
      "quantity": 2
    },
    {
      "product": 5000123,
      "shop": 2,
      "quantity": 1
    }
  ]
}

###

POST {{BASE_URL}}/contacts/
Content-Type: application/json
Authorization: Token 8b62e9e08c4c639ff2f4fd5de7cb6f8e3eecb15a

{
  "type": "telegram",
  "value": "doshamine"
}

###

POST {{BASE_URL}}/contacts/
Content-Type: application/json
Authorization: Token 159a35622c240a0052b168c692ab918be83a6f9c

{
  "type": "address",
  "value": "world"
}

###

POST {{BASE_URL}}/confirm/
Content-Type: application/json
Authorization: Token 159a35622c240a0052b168c692ab918be83a6f9c

{
  "order_id": 1,
  "contact_id": 1
}

###

GET {{BASE_URL}}/orders/
Content-Type: application/json
Authorization: Token 159a35622c240a0052b168c692ab918be83a6f9c