@BASE_URL = http://localhost:8000/api/v1
@TOKEN = 92ab967bef2423c09f2ddf50ed6cd97ae1754bef


POST {{BASE_URL}}/register/
Content-Type: application/json

{
  "username": "doshamine",
  "first_name": "Иван",
  "last_name": "Иванов",
  "email": "doshamine@gmail.com",
  "password": "123"
}

###

POST {{BASE_URL}}/login/
Content-Type: application/json

{
  "username": "doshamine",
  "password": "123"
}

###

GET {{BASE_URL}}/products/?shop_id=1&max_price=1000
Content-Type: application/json
Authorization: Token {{TOKEN}}

###

GET {{BASE_URL}}/orders/
Content-Type: application/json
Authorization: Token {{TOKEN}}

###

PATCH {{BASE_URL}}/cart/1/
Content-Type: application/json
Authorization: Token {{TOKEN}}

{
  "status": "canceled"
}

###

POST {{BASE_URL}}/orders/
Content-Type: application/json
Authorization: Token {{TOKEN}}

{
  "order_items": [
    {
      "product": 1235464569,
      "shop": 1,
      "quantity": 2
    },
    {
      "product": 5000123,
      "shop": 2,
      "quantity": 1
    }
  ]
}

###

GET {{BASE_URL}}/contacts/1
Content-Type: application/json
Authorization: Token {{TOKEN}}

###

PATCH {{BASE_URL}}/contacts/2/
Content-Type: application/json
Authorization: Token {{TOKEN}}

{
  "type": "phone",
  "value": "666"
}

###

POST {{BASE_URL}}/confirm/
Content-Type: application/json
Authorization: Token {{TOKEN}}

{
  "order_id": 3,
  "contact_id": 1
}

###

GET {{BASE_URL}}/orders/
Content-Type: application/json
Authorization: Token {{TOKEN}}