# Generated by Django 5.2.3 on 2025-06-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_product_model_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='url',
            field=models.URLField(unique=True, verbose_name='url'),
        ),
    ]
