# Generated by Django 5.2.2 on 2025-06-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('address', 'адрес'), ('email', 'почта'), ('phone', 'телефон'), ('telegram', 'телеграм')], max_length=50, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='value',
            field=models.CharField(max_length=100, verbose_name='value'),
        ),
    ]
